image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    # We'll also build whenever there is a new commit on any branch starting with `features/` or `hotfix/`
    - /features\/.+/
    - /hotfix\/.+/
build_script:
  - ps: |
      dotnet cake build.cake --bootstrap
      dotnet cake build.cake --pack
assembly_info:
  # There is nothing to version except the `GitHub` release
  patch: false
# We'll run the tests in the build script
test: off
# AppVeyor will create a release tag if a matching one does not exist
# hence triggering another build
skip_tags: true
skip_commits:
  files:
    - .editorconfig
    - LICENSE
    - README.md
deploy:
  # The provider is case sensitive
  - provider: GitHub
    # By convention release versions start with `v`
    release: v$(APPVEYOR_BUILD_VERSION)
    auth_token:
      # Encrypted `GitHub` `PAT`
      # https://www.appveyor.com/docs/deployment/github/#provider-settings
      secure: AmCNluoUjQddLCZrNghd0XjLwFhrofDMF7UTdmJDLuK5g/+FKGfBr6IOIbN3hrRw
    artifact: transform,packages
    draft: false
    prerelease: false
    on:
      branch: master
  - provider: NuGet
    server: https://www.nuget.org/api/v2/package
    api_key:
      # Encrypted `NuGet.org` token - https://www.nuget.org/account/ApiKeys
      # https://www.appveyor.com/docs/deployment/nuget/#provider-settings
      secure: nzQzvnwJXR6gW+3wS8yD5+jTJt4ohQBOisJ450RcDqgRtcmCgBNCfGH2KHvfPPZ4
    skip_symbols: false
    symbol_server: https://nuget.smbsrc.net/
    artifact: packages
    on:
      branch: master
  - provider: GitHub
    # By convention release versions start with `v`
    release: v$(APPVEYOR_BUILD_VERSION)
    auth_token:
      # Encrypted `GitHub` `PAT`
      # https://www.appveyor.com/docs/deployment/github/#provider-settings
      secure: AmCNluoUjQddLCZrNghd0XjLwFhrofDMF7UTdmJDLuK5g/+FKGfBr6IOIbN3hrRw
    artifact: transform,packages
    draft: false
    prerelease: true
    on:
      branch: /features\/.+/
  - provider: NuGet
    server: https://www.myget.org/F/gabrielweyer-pre-release/api/v2/package
    api_key:
      # Encrypted `MyGet` token - https://www.myget.org/profile/Me#!/AccessTokens
      # https://www.appveyor.com/docs/deployment/nuget/#provider-settings
      secure: Mw3OOYIQt9LVVJ+STxrwec8mEB+OSQX1ba3zccnm05MvvBiceV4C09N++rgplgtB
    skip_symbols: false
    symbol_server: https://www.myget.org/F/gabrielweyer-pre-release/symbols/api/v2/package
    artifact: packages
    on:
      branch: /features\/.+/
# Environment variables
environment:
  # No need to pre-warm the `NuGet` cache
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
# `install` will run before `build_script`
install:
  # `XsltTests` is targeting `netcoreapp2.1`, so we can safely install the latest `SDK`
  # The `SDK` is required to restore, build, publish... a `.NET Core` application
  # https://www.microsoft.com/net/download/windows
  - ps: .\setup\dotnet-install.ps1 -Channel Current
  - ps: dotnet tool install --global Cake.Tool --version 0.31.0
