image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    # We'll also build whenever there is a new commit on any branch starting with `features/`
    - /features\/.+/
build_script:
  - ps: .\build.ps1 -pack
assembly_info:
  # There is nothing to version except the `GitHub` release
  patch: false
# We'll run the tests in the build script
test: off
# AppVeyor will create a release tag if a matching one does not exist
# hence triggering another build
skip_tags: true
skip_commits:
  files:
    - .editorconfig
    - LICENSE
    - README.md
deploy:
  # The provider is case sensitive
  - provider: GitHub
    # By convention release versions start with `v`
    release: v$(APPVEYOR_BUILD_VERSION)
    auth_token:
      # Encrypted `GitHub` `PAT`
      # https://www.appveyor.com/docs/deployment/github/#provider-settings
      secure: AmCNluoUjQddLCZrNghd0XjLwFhrofDMF7UTdmJDLuK5g/+FKGfBr6IOIbN3hrRw
    artifact: transform,packages
    draft: false
    prerelease: false
    on:
      branch: master
  - provider: NuGet
    server: https://www.nuget.org/api/v2/package
    api_key:
      # Encrypted `NuGet.org` token - https://www.nuget.org/account/ApiKeys
      # https://www.appveyor.com/docs/deployment/nuget/#provider-settings
      secure: IFDjCibNCjADjEU1fMIu+O8Jhe0Q4dBMM58kT3muEMISJLYEZlCTDpZ5y4WtdPIs
    skip_symbols: false
    symbol_server: https://nuget.smbsrc.net/
    artifact: packages
    on:
      branch: master
  - provider: GitHub
    # By convention release versions start with `v`
    release: v$(APPVEYOR_BUILD_VERSION)
    auth_token:
      # Encrypted `GitHub` `PAT`
      # https://www.appveyor.com/docs/deployment/github/#provider-settings
      secure: AmCNluoUjQddLCZrNghd0XjLwFhrofDMF7UTdmJDLuK5g/+FKGfBr6IOIbN3hrRw
    artifact: transform,packages
    draft: false
    prerelease: true
    on:
      branch: /features\/.+/
  - provider: NuGet
    server: https://www.myget.org/F/gabrielweyer-pre-release/api/v2/package
    api_key:
      # Encrypted `MyGet` token - https://www.myget.org/profile/Me#!/AccessTokens
      # https://www.appveyor.com/docs/deployment/nuget/#provider-settings
      secure: 5LLnFMrZETquTfl10cGML5CoozXgD0ULTWLlSjsi/oQi0XN0beUPM3O7Nsz8AK/d
    skip_symbols: false
    symbol_server: https://www.myget.org/F/gabrielweyer-pre-release/symbols/api/v2/package
    artifact: packages
    on:
      branch: /features\/.+/
# Environment variables
environment:
  # No need to pre-warm the `NuGet` cache
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
# `install` will run before `build_script`
install:
  # `dotnet-install.ps1` is available at: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script
  # `Cake.dll` is targeting `.NET Core` `1.0.9`, so we need to install the latest `1.0.x` runtime
  # The runtime is required to run a `.NET Core` application, it's part of the `SDK`
  # https://github.com/dotnet/core/blob/master/release-notes/download-archive.md
  - ps: .\setup\dotnet-install.ps1 -SharedRuntime -Version 1.0.9
  # `XsltTests` is targeting `netcoreapp2.0`, so we can safely install the latest `SDK`
  # The `SDK` is required to restore, build, publish... a `.NET Core` application
  # https://www.microsoft.com/net/download/windows
  - ps: .\setup\dotnet-install.ps1 -Channel Current
